import type { Doctor, DoctorsSectionContent } from "@/types/content";

export const doctorsSection = {
  eyebrow: "Find a Doctor",
  heading: "Every referral here has a name attached.",
  lead: "These are four of the physicians who lead our services. Call the appointment line and ask for any of them by name.",
  bookWithLabel: "Book with Dr.",
  languagesLabel: "Speaks",
  acceptingLabel: "Accepting new patients",
  notAcceptingLabel: "Not accepting new patients",
  moreLabel: "Also practising here:",
  languageNames: {
    en: "English",
    es: "Spanish",
    pt: "Portuguese",
    fr: "French",
    zh: "Mandarin",
    ar: "Arabic",
  },
} as const satisfies DoctorsSectionContent;

/**
 * Twelve invented physicians for an invented hospital; the footer disclaimer
 * covers them. `photo.src` is `null` for all twelve and the card renders a
 * monogram: a stock or generated face would put a real person's likeness
 * behind a physician who does not exist, which no amount of "it's fictional"
 * makes fine. The 600x800 dimensions are already in the record so the switch
 * to real portraits is a one-field edit with no layout drift.
 *
 * `education` and `boardCertifications` name real institutions, following the
 * worked example in PLAN.md §4.4. Neither renders in v1 — they are here for
 * the v2 detail page and the chat's grounding corpus.
 */
const photoOf = (name: string) =>
  ({
    src: null,
    alt: `Portrait of ${name}`,
    width: 600,
    height: 800,
  }) as const;

export const doctors = [
  {
    slug: "amara-okafor",
    firstName: "Amara",
    lastName: "Okafor",
    credentials: ["MD", "FACC"],
    title: "Chief of Cardiology",
    primarySpecialtySlug: "cardiology",
    specialtySlugs: ["cardiology"],
    photo: photoOf("Dr. Amara Okafor"),
    bio: "Dr. Okafor leads the interventional cardiology programme and runs the clinic for patients living with heart failure. She sees prevention and intervention as one service rather than two.",
    education: [
      {
        institution: "Johns Hopkins University School of Medicine",
        degree: "MD",
        year: 2006,
      },
      {
        institution: "Massachusetts General Hospital",
        degree: "Residency, Internal Medicine",
        year: 2009,
      },
    ],
    boardCertifications: [
      "American Board of Internal Medicine — Cardiovascular Disease",
    ],
    languages: ["en", "fr"],
    yearsOfExperience: 18,
    locationSlugs: ["main-campus"],
    acceptingNewPatients: true,
    featured: true,
    order: 1,
    booking: {
      enabled: true,
      providerId: null,
      appointmentTypes: ["new-patient", "follow-up", "telehealth"],
    },
  },
  {
    slug: "daniel-reyes",
    firstName: "Daniel",
    lastName: "Reyes",
    credentials: ["MD"],
    title: "Director of the Stroke Program",
    primarySpecialtySlug: "neurology",
    specialtySlugs: ["neurology", "emergency-medicine"],
    photo: photoOf("Dr. Daniel Reyes"),
    bio: "Dr. Reyes built the stroke pathway that runs imaging, assessment and treatment in parallel from the moment a patient arrives. He also holds a weekly clinic for epilepsy.",
    education: [
      {
        institution: "University of California, San Francisco",
        degree: "MD",
        year: 2004,
      },
      {
        institution: "Brigham and Women's Hospital",
        degree: "Fellowship, Vascular Neurology",
        year: 2011,
      },
    ],
    boardCertifications: [
      "American Board of Psychiatry and Neurology — Neurology",
      "American Board of Psychiatry and Neurology — Vascular Neurology",
    ],
    languages: ["en", "es"],
    yearsOfExperience: 21,
    locationSlugs: ["main-campus"],
    acceptingNewPatients: true,
    featured: true,
    order: 2,
    booking: {
      enabled: true,
      providerId: null,
      appointmentTypes: ["new-patient", "follow-up", "second-opinion"],
    },
  },
  {
    slug: "priya-raghunathan",
    firstName: "Priya",
    lastName: "Raghunathan",
    credentials: ["MD", "FACS"],
    title: "Orthopedic Surgeon",
    primarySpecialtySlug: "orthopedics",
    specialtySlugs: ["orthopedics"],
    photo: photoOf("Dr. Priya Raghunathan"),
    bio: "Dr. Raghunathan operates on hips and knees and runs the sports medicine clinic. She starts every plan with the physical therapy that follows the surgery, not after it.",
    education: [
      {
        institution: "Weill Cornell Medical College",
        degree: "MD",
        year: 2009,
      },
      {
        institution: "Hospital for Special Surgery",
        degree: "Fellowship, Adult Reconstruction",
        year: 2016,
      },
    ],
    boardCertifications: ["American Board of Orthopaedic Surgery"],
    languages: ["en"],
    yearsOfExperience: 16,
    locationSlugs: ["main-campus"],
    acceptingNewPatients: true,
    featured: true,
    order: 3,
    booking: {
      enabled: true,
      providerId: null,
      appointmentTypes: ["new-patient", "follow-up", "second-opinion"],
    },
  },
  {
    slug: "helen-mbeki",
    firstName: "Helen",
    lastName: "Mbeki",
    credentials: ["MD"],
    title: "Medical Oncologist",
    primarySpecialtySlug: "oncology",
    specialtySlugs: ["oncology"],
    photo: photoOf("Dr. Helen Mbeki"),
    bio: "Dr. Mbeki chairs the tumor board that brings medical oncology, radiation oncology and surgery into one room before a treatment plan is agreed. Her clinic focuses on breast and colorectal cancer.",
    education: [
      {
        institution: "University of Michigan Medical School",
        degree: "MD",
        year: 2008,
      },
      {
        institution: "Dana-Farber Cancer Institute",
        degree: "Fellowship, Hematology and Oncology",
        year: 2014,
      },
    ],
    boardCertifications: [
      "American Board of Internal Medicine — Medical Oncology",
    ],
    languages: ["en", "fr"],
    yearsOfExperience: 17,
    locationSlugs: ["main-campus"],
    acceptingNewPatients: true,
    featured: true,
    order: 4,
    booking: {
      enabled: true,
      providerId: null,
      appointmentTypes: ["new-patient", "follow-up", "second-opinion"],
    },
  },
  {
    slug: "sofia-marchetti",
    firstName: "Sofia",
    lastName: "Marchetti",
    credentials: ["MD", "FACOG"],
    title: "Chief of Obstetrics and Gynecology",
    primarySpecialtySlug: "womens-health",
    specialtySlugs: ["womens-health"],
    photo: photoOf("Dr. Sofia Marchetti"),
    bio: "Dr. Marchetti leads the maternity service and keeps the same team with a patient from the first prenatal visit through the postpartum weeks.",
    education: [
      {
        institution: "Yale School of Medicine",
        degree: "MD",
        year: 2007,
      },
      {
        institution: "Beth Israel Deaconess Medical Center",
        degree: "Residency, Obstetrics and Gynecology",
        year: 2011,
      },
    ],
    boardCertifications: ["American Board of Obstetrics and Gynecology"],
    languages: ["en", "es"],
    yearsOfExperience: 18,
    locationSlugs: ["main-campus"],
    acceptingNewPatients: true,
    featured: false,
    order: 5,
    booking: {
      enabled: true,
      providerId: null,
      appointmentTypes: ["new-patient", "follow-up", "telehealth"],
    },
  },
  {
    slug: "james-whitlock",
    firstName: "James",
    lastName: "Whitlock",
    credentials: ["DO"],
    title: "Primary Care Physician",
    primarySpecialtySlug: "primary-care",
    specialtySlugs: ["primary-care"],
    photo: photoOf("Dr. James Whitlock"),
    bio: "Dr. Whitlock has kept the same panel of patients for over a decade. He handles annual physicals, blood pressure, diabetes and the referrals that open every other service here.",
    education: [
      {
        institution: "Philadelphia College of Osteopathic Medicine",
        degree: "DO",
        year: 2010,
      },
      {
        institution: "Baystate Medical Center",
        degree: "Residency, Family Medicine",
        year: 2013,
      },
    ],
    boardCertifications: ["American Board of Family Medicine"],
    languages: ["en"],
    yearsOfExperience: 15,
    locationSlugs: ["main-campus"],
    acceptingNewPatients: false,
    featured: false,
    order: 6,
    booking: {
      enabled: true,
      providerId: null,
      appointmentTypes: ["follow-up", "annual-physical", "telehealth"],
    },
  },
  {
    slug: "yusuf-demir",
    firstName: "Yusuf",
    lastName: "Demir",
    credentials: ["MD", "FACEP"],
    title: "Emergency Medicine Physician",
    primarySpecialtySlug: "emergency-medicine",
    specialtySlugs: ["emergency-medicine"],
    photo: photoOf("Dr. Yusuf Demir"),
    bio: "Dr. Demir works the emergency department floor and runs the observation unit. He led the redesign of how patients are triaged on arrival.",
    education: [
      {
        institution: "Icahn School of Medicine at Mount Sinai",
        degree: "MD",
        year: 2011,
      },
      {
        institution: "Boston Medical Center",
        degree: "Residency, Emergency Medicine",
        year: 2015,
      },
    ],
    boardCertifications: ["American Board of Emergency Medicine"],
    languages: ["en", "ar"],
    yearsOfExperience: 14,
    locationSlugs: ["main-campus"],
    acceptingNewPatients: true,
    featured: false,
    order: 7,
    booking: {
      enabled: false,
      providerId: null,
      appointmentTypes: [],
    },
  },
  {
    slug: "clara-nguyen",
    firstName: "Clara",
    lastName: "Nguyen",
    credentials: ["MD"],
    title: "Diagnostic Radiologist",
    primarySpecialtySlug: "imaging",
    specialtySlugs: ["imaging", "oncology"],
    photo: photoOf("Dr. Clara Nguyen"),
    bio: "Dr. Nguyen reads on the same campus as the teams that order the studies, which is what lets a clinic visit end with an answer. Her subspecialty is oncologic imaging.",
    education: [
      {
        institution: "Duke University School of Medicine",
        degree: "MD",
        year: 2012,
      },
      {
        institution: "Massachusetts General Hospital",
        degree: "Fellowship, Body Imaging",
        year: 2018,
      },
    ],
    boardCertifications: ["American Board of Radiology — Diagnostic Radiology"],
    languages: ["en", "zh"],
    yearsOfExperience: 13,
    locationSlugs: ["main-campus"],
    acceptingNewPatients: true,
    featured: false,
    order: 8,
    booking: {
      enabled: true,
      providerId: null,
      appointmentTypes: ["new-patient"],
    },
  },
  {
    slug: "thomas-obrien",
    firstName: "Thomas",
    lastName: "O'Brien",
    credentials: ["MD"],
    title: "Ophthalmologist",
    primarySpecialtySlug: "ophthalmology",
    specialtySlugs: ["ophthalmology"],
    photo: photoOf("Dr. Thomas O'Brien"),
    bio: "Dr. O'Brien performs cataract surgery and manages glaucoma. He runs the retinal screening clinic for patients living with diabetes.",
    education: [
      {
        institution: "Trinity College Dublin School of Medicine",
        degree: "MB BCh BAO",
        year: 2005,
      },
      {
        institution: "Massachusetts Eye and Ear",
        degree: "Fellowship, Glaucoma",
        year: 2013,
      },
    ],
    boardCertifications: ["American Board of Ophthalmology"],
    languages: ["en"],
    yearsOfExperience: 20,
    locationSlugs: ["main-campus"],
    acceptingNewPatients: true,
    featured: false,
    order: 9,
    booking: {
      enabled: true,
      providerId: null,
      appointmentTypes: ["new-patient", "follow-up"],
    },
  },
  {
    slug: "ana-lucia-ferreira",
    firstName: "Ana Lúcia",
    lastName: "Ferreira",
    credentials: ["MD", "PhD"],
    title: "Director of Laboratory Medicine",
    primarySpecialtySlug: "laboratory",
    specialtySlugs: ["laboratory", "oncology"],
    photo: photoOf("Dr. Ana Lúcia Ferreira"),
    bio: "Dr. Ferreira runs pathology and microbiology on campus and sits on the tumor board. Her research background is in molecular diagnostics.",
    education: [
      {
        institution: "Universidade de São Paulo",
        degree: "MD",
        year: 2003,
      },
      {
        institution: "Washington University in St. Louis",
        degree: "PhD, Molecular Pathology",
        year: 2010,
      },
    ],
    boardCertifications: [
      "American Board of Pathology — Anatomic and Clinical Pathology",
    ],
    languages: ["en", "pt", "es"],
    yearsOfExperience: 22,
    locationSlugs: ["main-campus"],
    acceptingNewPatients: false,
    featured: false,
    order: 10,
    booking: {
      enabled: false,
      providerId: null,
      appointmentTypes: [],
    },
  },
  {
    slug: "marcus-hollis",
    firstName: "Marcus",
    lastName: "Hollis",
    credentials: ["MD"],
    title: "Cardiologist",
    primarySpecialtySlug: "cardiology",
    specialtySlugs: ["cardiology", "primary-care"],
    photo: photoOf("Dr. Marcus Hollis"),
    bio: "Dr. Hollis runs the cardiac rehabilitation programme and the clinic for atrial fibrillation. He works closely with primary care on blood pressure and cholesterol.",
    education: [
      {
        institution: "Emory University School of Medicine",
        degree: "MD",
        year: 2013,
      },
      {
        institution: "Tufts Medical Center",
        degree: "Fellowship, Cardiovascular Disease",
        year: 2019,
      },
    ],
    boardCertifications: [
      "American Board of Internal Medicine — Cardiovascular Disease",
    ],
    languages: ["en"],
    yearsOfExperience: 12,
    locationSlugs: ["main-campus"],
    acceptingNewPatients: true,
    featured: false,
    order: 11,
    booking: {
      enabled: true,
      providerId: null,
      appointmentTypes: ["new-patient", "follow-up", "telehealth"],
    },
  },
  {
    slug: "leila-haddad",
    firstName: "Leila",
    lastName: "Haddad",
    credentials: ["MD", "FAAP"],
    title: "Family Medicine Physician",
    primarySpecialtySlug: "primary-care",
    specialtySlugs: ["primary-care", "womens-health"],
    photo: photoOf("Dr. Leila Haddad"),
    bio: "Dr. Haddad looks after whole families, from newborn checks through to adult chronic care, and keeps the histories connected across them.",
    education: [
      {
        institution: "American University of Beirut Faculty of Medicine",
        degree: "MD",
        year: 2012,
      },
      {
        institution: "Lahey Hospital and Medical Center",
        degree: "Residency, Family Medicine",
        year: 2016,
      },
    ],
    boardCertifications: [
      "American Board of Family Medicine",
      "American Board of Pediatrics",
    ],
    languages: ["en", "ar", "fr"],
    yearsOfExperience: 13,
    locationSlugs: ["main-campus"],
    acceptingNewPatients: true,
    featured: false,
    order: 12,
    booking: {
      enabled: true,
      providerId: null,
      appointmentTypes: ["new-patient", "annual-physical", "telehealth"],
    },
  },
] as const satisfies readonly Doctor[];
